### PR TITLE
Use NodeJS 20 + use clean env for building

### PR DESCRIPTION
**Pull request by orhtej2**
- Upstream uses NodeJS 20 for building.
- #21

### CODE REVIEW

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by orhtej2** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
